<?php

declare(strict_types=1);

/**
 * Variables provided by PhpTemplateRenderer::extract($context)
 * @var mixed $entity_class
 * @var mixed $extension_type
 * @var mixed $impact
 * @var mixed $context
 */
$entity_class = (string) ($context['entity_class'] ?? '');
$extension_type = (string) ($context['extension_type'] ?? '');
$impact = (string) ($context['impact'] ?? '');
$e = fn (?string $str): string => htmlspecialchars($str ?? '', ENT_QUOTES, 'UTF-8');
ob_start();
?>
<div class="suggestion-header"><h4>Suggestion</h4></div>
<div class="suggestion-content">
<p>The entity <?php echo $e($entity_class); ?> uses Gedmo <?php echo $e($extension_type); ?> extension, which <?php echo $e($impact); ?>.</p>

<h4>Understanding the Impact</h4>
<?php if ('Loggable' === $extension_type): ?>
<p><strong>Gedmo Loggable</strong> automatically creates audit log entries for tracked fields:</p>
<ul>
<li>Each field change triggers an INSERT into the changelog table</li>
<li>With 10 fields and 1000 updates per day, that's 10,000 additional INSERTs</li>
<li>Log tables grow unbounded — cleanup policies must be implemented</li>
<li>Query performance degrades as log tables grow</li>
</ul>

<h4>Alternatives to Consider</h4>
<ul>
<li><strong>Application-level auditing</strong> — Log changes in your application code only for critical fields</li>
<li><strong>Database-level triggers</strong> — Use native database triggers for better performance</li>
<li><strong>Event listeners</strong> — Implement Doctrine lifecycle callbacks instead of Gedmo</li>
<li><strong>No auditing for non-critical entities</strong> — Audit only high-value data</li>
</ul>

<h4>If you keep Loggable</h4>
<ul>
<li>Monitor the changelog table size regularly</li>
<li>Implement archive or cleanup policies</li>
<li>Consider using <code>#[Versioned]</code> only on critical fields, not all</li>
<li>Profile your application to measure the actual impact</li>
</ul>
<?php elseif ('Translatable' === $extension_type): ?>
<p><strong>Gedmo Translatable</strong> manages translations in separate tables:</p>
<ul>
<li>Each translatable field generates queries for each active locale</li>
<li>With 3 translatable fields and 5 locales, that's 15 additional queries per entity load</li>
<li>Query count scales linearly with locales — regional expansion multiplies queries</li>
<li>Consider caching strategies to mitigate the impact</li>
</ul>

<h4>Alternatives to Consider</h4>
<ul>
<li><strong>Denormalized translations</strong> — Store translations in the main table (JSON columns)</li>
<li><strong>Key-value translation store</strong> — Separate service for translation management</li>
<li><strong>Database-level i18n</strong> — Use native PostgreSQL jsonb or MySQL JSON type</li>
<li><strong>Third-party services</strong> — Offload translation management to specialized services</li>
</ul>

<h4>If you keep Translatable</h4>
<ul>
<li>Use eager loading for translations in frequently accessed queries</li>
<li>Implement query result caching at the application level</li>
<li>Consider limiting the number of active locales</li>
<li>Monitor query performance during locale expansion</li>
</ul>
<?php endif; ?>

<h4>Monitoring</h4>
<ul>
<li>Use the Web Profiler to track queries generated by <?php echo $e($extension_type); ?></li>
<li>Compare baseline queries with and without the extension</li>
<li>Profile high-traffic code paths to measure real-world impact</li>
</ul>
</div>
<?php
$code = ob_get_clean();

return ['code' => $code, 'description' => 'Entity uses Gedmo ' . $extension_type . ' which generates additional queries — review performance impact'];
