<?php

declare(strict_types=1);

/** @var array<string, mixed> $context */
$entityClass = (string) ($context['entity_class'] ?? 'Entity');
$fieldName = (string) ($context['field_name'] ?? 'id');

$e = fn (?string $str): string => htmlspecialchars($str ?? '', ENT_QUOTES, 'UTF-8');

ob_start();
?>

<div class="suggestion-header">
    <h4>Nullable Primary Key: <?php echo $e($entityClass); ?></h4>
</div>

<div class="suggestion-content">
    <div class="alert alert-warning">
        Field <code><?php echo $e($fieldName); ?></code> is part of the primary key and declares
        <code>nullable: true</code>. A primary key cannot hold NULL, so the flag never reaches the schema.
        Doctrine ORM 3.6 deprecated it and ORM 4.0 rejects it.
    </div>

    <h4>Before</h4>
    <div class="query-item">
        <pre><code class="language-php">#[ORM\Id]
#[ORM\Column(nullable: true)]
private ?int $<?php echo $e($fieldName); ?> = null;</code></pre>
    </div>

    <h4>After</h4>
    <div class="query-item">
        <pre><code class="language-php">#[ORM\Id]
#[ORM\Column]
private ?int $<?php echo $e($fieldName); ?> = null;</code></pre>
    </div>

    <p>The PHP property stays nullable when the identifier is generated by the database:
    it holds <code>null</code> until the entity is flushed. Only the column mapping changes,
    so no migration is generated.</p>
</div>

<?php
$html = (string) ob_get_clean();

return [
    'code' => $html,
    'description' => sprintf(
        'Remove nullable from the primary key %s::$%s',
        $entityClass,
        $fieldName,
    ),
];
